name: pygmt
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - pip
    - gmt=6.1.1
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - ipython
    - matplotlib
    - jupyter
    - pytest>=6.0
    - pytest-cov
    - pytest-mpl
    - coverage[toml]
    - black
    - blackdoc
    - docformatter
    - pylint
    - flake8
    - sphinx
    - sphinx_rtd_theme=0.4.3
    - sphinx-gallery
    - nbsphinx
